name: clear_servis
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  firebase_core: ^2.4.1
  firebase_auth: ^4.4.0
  provider: ^6.0.0
  http: ^0.13.3
  intl: ^0.17.0
  html: ^0.15.0
  flutter_rating_bar: ^4.0.0
  google_sign_in: ^5.0.7
  flutter_facebook_auth: ^6.0.4
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  assets:
    - assets/images/italki_logo.png
  uses-material-design: true
