name: clear_servis_new
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.2
  http: ^1.0.0
  intl: ^0.19.0
  html: ^0.15.0
  flutter_rating_bar: ^4.0.0
  cupertino_icons: ^1.0.5
  intl_phone_field: ^3.1.0
  geolocator: ^12.0.0
  geocoding: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0


flutter:
  assets:
    - assets/images/AppBar.png
    - assets/images/italki_logo.png
  uses-material-design: true
